title: "SIDHANT THAKUR"
email: sidthakur2001@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
TECH ENTHUSIAST,QUICK LEARNER AND A BEGINNER IN THE FIELD OF IT,knows basic workflow and basic frontend development :)
baseurl: "/" 
url: "https://SIDHANT2001.github.io/" 
twitter_username: sidhantthakur3
github_username:  SIDHANT2001

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
